/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car.rental;


import java.awt.Color;

/**
 *
 * @author amjad
 */
public class car extends javax.swing.JPanel {

    /**
     * Creates new form car
     */
    public car() {
        initComponents();
       // t1.enable(false);
        //t2.enable(false);
        save.setOpaque(false);
        save.setContentAreaFilled(false); //to make the content area transparent
        save.setBorderPainted(false);
        back.setOpaque(false);
        back.setContentAreaFilled(false); //to make the content area transparent
        back.setBorderPainted(false);
        group1.add(ger1);
        group1.add(atumat);
        group2.add(b12);
        group2.add(d12);
        
        
      
    }

       public class shi1 extends Thread
   {
       public void run()
       {
           while (true)
           {
               if(FirstFrame.Car.getY()>=1100)
                       return;
            try 
            {
                Thread.sleep(1);
            } catch (InterruptedException ex) 
            {}
            FirstFrame.Car.setLocation(FirstFrame.Car.getX(), FirstFrame.Car.getY()+1);
           }
       
       }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        atumat = new javax.swing.JRadioButton();
        b12 = new javax.swing.JRadioButton();
        ger1 = new javax.swing.JRadioButton();
        d12 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        atumat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        atumat.setText("Auto");
        add(atumat);
        atumat.setBounds(180, 340, 80, 30);

        b12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        b12.setText("Benz");
        add(b12);
        b12.setBounds(100, 370, 70, 30);

        ger1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ger1.setSelected(true);
        ger1.setText("Manual");
        ger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ger1ActionPerformed(evt);
            }
        });
        add(ger1);
        ger1.setBounds(100, 340, 80, 30);

        d12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        d12.setText("Diesel");
        d12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d12ActionPerformed(evt);
            }
        });
        add(d12);
        d12.setBounds(170, 370, 70, 30);

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(120, 310, 70, 20);
        add(save);
        save.setBounds(80, 720, 33, 9);

        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back);
        back.setBounds(220, 720, 33, 9);

        jTextField11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField11.setText("License Date");
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        add(jTextField11);
        jTextField11.setBounds(20, 220, 240, 20);

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel1.setText("Car Information");
        add(jLabel1);
        jLabel1.setBounds(70, 10, 220, 40);

        jLabel2.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jLabel2.setText("Gear type :");
        add(jLabel2);
        jLabel2.setBounds(20, 340, 80, 30);

        jTextField13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField13.setText("car name");
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });
        jTextField13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField13MouseClicked(evt);
            }
        });
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        add(jTextField13);
        jTextField13.setBounds(20, 70, 240, 20);

        jTextField14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField14.setText("Color");
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField14FocusLost(evt);
            }
        });
        jTextField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField14MouseClicked(evt);
            }
        });
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        add(jTextField14);
        jTextField14.setBounds(20, 100, 240, 20);

        jTextField15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField15.setText("Number in company");
        jTextField15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField15FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField15FocusLost(evt);
            }
        });
        jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField15MouseClicked(evt);
            }
        });
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        add(jTextField15);
        jTextField15.setBounds(20, 130, 240, 20);

        jTextField16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField16.setText("Capacity");
        jTextField16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField16FocusLost(evt);
            }
        });
        jTextField16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField16MouseClicked(evt);
            }
        });
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        add(jTextField16);
        jTextField16.setBounds(20, 160, 240, 20);

        jTextField12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField12.setText("Price");
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        add(jTextField12);
        jTextField12.setBounds(20, 280, 240, 20);

        jTextField17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField17.setText("Plate Number");
        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField17FocusLost(evt);
            }
        });
        jTextField17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField17MouseClicked(evt);
            }
        });
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        add(jTextField17);
        jTextField17.setBounds(20, 190, 240, 20);

        jTextField18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField18.setText("Insurance Date");
        jTextField18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField18FocusLost(evt);
            }
        });
        jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField18MouseClicked(evt);
            }
        });
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        add(jTextField18);
        jTextField18.setBounds(20, 250, 240, 20);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Fuel Type :");
        add(jLabel3);
        jLabel3.setBounds(20, 370, 90, 26);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Product Year :");
        add(jLabel4);
        jLabel4.setBounds(20, 310, 120, 19);

        jButton1.setText("save");
        add(jButton1);
        jButton1.setBounds(30, 440, 80, 40);

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(160, 440, 90, 40);
    }// </editor-fold>//GEN-END:initComponents

    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
shi1 s=new shi1();
s.start();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void ger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ger1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ger1ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        if(jTextField13.getText().equals(""))
        jTextField13.setText("car name");   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13FocusLost

    private void jTextField13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField13MouseClicked
        if(jTextField13.getText().equals("car name"))
        jTextField13.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13MouseClicked

    private void jTextField14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusLost
       if(jTextField14.getText().equals(""))
        jTextField14.setText("Color"); 
    }//GEN-LAST:event_jTextField14FocusLost

    private void jTextField14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField14MouseClicked
       if(jTextField14.getText().equals("Color"))
        jTextField14.setText(""); 
    }//GEN-LAST:event_jTextField14MouseClicked

    private void jTextField15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField15FocusLost
       if(jTextField15.getText().equals(""))
        jTextField15.setText("Number in company") ;// TODO add your handling code here:
    }//GEN-LAST:event_jTextField15FocusLost

    private void jTextField15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField15MouseClicked
 if(jTextField15.getText().equals("Number in company"))
  jTextField15.setText("");     }//GEN-LAST:event_jTextField15MouseClicked

    private void jTextField16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField16FocusLost
      if(jTextField16.getText().equals(""))
        jTextField16.setText("Capacity");  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16FocusLost

    private void jTextField16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField16MouseClicked
      if(jTextField16.getText().equals("Capacity"))
        jTextField16.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16MouseClicked

    private void jTextField17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField17FocusLost
     if(jTextField17.getText().equals(""))
        jTextField17.setText("Plate Number");   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17FocusLost

    private void jTextField17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField17MouseClicked
     if(jTextField17.getText().equals("Plate Number"))
        jTextField17.setText("");   // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17MouseClicked

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
   if(jTextField11.getText().equals(""))
        jTextField11.setText("License Date")  ;
   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        if(jTextField11.getText().equals("License Date"))
        jTextField11.setText("") ;  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField18FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField18FocusLost
       if(jTextField18.getText().equals(""))
        jTextField18.setText("Insurance Date"); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18FocusLost

    private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField18MouseClicked
        if(jTextField18.getText().equals("Insurance Date"))
        jTextField18.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18MouseClicked

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
      if(jTextField12.getText().equals(""))
        jTextField12.setText("Price") ; // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12FocusLost

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        if(jTextField12.getText().equals("Price"))
        jTextField12.setText("") ;         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12MouseClicked

    private void d12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d12ActionPerformed

    private void jTextField15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField15FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15FocusGained

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
         if(jTextField13.getText().equals(""))
        jTextField13.setText("car name"); 
           if(jTextField14.getText().equals(""))
        jTextField14.setText("Color"); 
             if(jTextField15.getText().equals(""))
        jTextField15.setText("Number in company");
              if(jTextField16.getText().equals(""))
        jTextField16.setText("Capacity");
               if(jTextField17.getText().equals(""))
        jTextField17.setText("Plate Number");
               if(jTextField11.getText().equals(""))
        jTextField11.setText("License Date") ;
                 if(jTextField12.getText().equals(""))
        jTextField12.setText("Price") ;
    }//GEN-LAST:event_formMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            shi1 s=new shi1();
            s.start();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton atumat;
    private javax.swing.JRadioButton b12;
    private javax.swing.JButton back;
    private javax.swing.JRadioButton d12;
    private javax.swing.JRadioButton ger1;
    private javax.swing.ButtonGroup group1;
    private javax.swing.ButtonGroup group2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
