/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car.rental;

/**
 *
 * @author mbp
 */
public class employee extends javax.swing.JPanel {

    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
        gg1.add(j1);
        gg1.add(j2);
        gg2.add(j3);
        gg2.add(j4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public class shi1 extends Thread
   {
       public void run()
       {
           while (true)
           {
               if(FirstFrame.ew.getY()>=1100)
                       return;
            try 
            {
                Thread.sleep(1);
            } catch (InterruptedException ex) 
            {}
           FirstFrame.ew.setLocation(FirstFrame.ew.getX(), FirstFrame.ew.getY()+1);
           }
       
       }
       
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gg1 = new javax.swing.ButtonGroup();
        gg2 = new javax.swing.ButtonGroup();
        j2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        firstnamefield2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        firstnamefield1 = new javax.swing.JTextField();
        j1 = new javax.swing.JRadioButton();
        firstnamefield4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        j4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        firstnamefield3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        j3 = new javax.swing.JRadioButton();
        firstnamefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setLayout(null);

        j2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        j2.setText("Unmarried");
        j2.setOpaque(false);
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        add(j2);
        j2.setBounds(190, 360, 90, 30);

        jLabel14.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        add(jLabel14);
        jLabel14.setBounds(30, 200, 60, 20);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(220, 440, 60, 60);

        jLabel20.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        add(jLabel20);
        jLabel20.setBounds(30, 300, 70, 20);

        jLabel13.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        add(jLabel13);
        jLabel13.setBounds(30, 150, 120, 20);

        jLabel18.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        add(jLabel18);
        jLabel18.setBounds(30, 250, 70, 20);

        firstnamefield2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        firstnamefield2.setText("Minit ");
        firstnamefield2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                firstnamefield2MouseDragged(evt);
            }
        });
        firstnamefield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefield2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefield2FocusLost(evt);
            }
        });
        firstnamefield2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefield2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                firstnamefield2MouseReleased(evt);
            }
        });
        firstnamefield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefield2ActionPerformed(evt);
            }
        });
        add(firstnamefield2);
        firstnamefield2.setBounds(60, 140, 230, 20);

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel19.setText("Status :");
        add(jLabel19);
        jLabel19.setBounds(60, 360, 50, 30);

        firstnamefield1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        firstnamefield1.setText("First Name ");
        firstnamefield1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                firstnamefield1MouseDragged(evt);
            }
        });
        firstnamefield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefield1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefield1FocusLost(evt);
            }
        });
        firstnamefield1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefield1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstnamefield1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                firstnamefield1MouseReleased(evt);
            }
        });
        firstnamefield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefield1ActionPerformed(evt);
            }
        });
        add(firstnamefield1);
        firstnamefield1.setBounds(60, 110, 230, 20);

        j1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        j1.setText("Married");
        j1.setOpaque(false);
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        add(j1);
        j1.setBounds(110, 360, 67, 30);

        firstnamefield4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        firstnamefield4.setText("Salary ");
        firstnamefield4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                firstnamefield4MouseDragged(evt);
            }
        });
        firstnamefield4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefield4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefield4FocusLost(evt);
            }
        });
        firstnamefield4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefield4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                firstnamefield4MouseReleased(evt);
            }
        });
        firstnamefield4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefield4ActionPerformed(evt);
            }
        });
        add(firstnamefield4);
        firstnamefield4.setBounds(60, 230, 230, 20);

        jTextField10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField10.setText("Id ");
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        add(jTextField10);
        jTextField10.setBounds(60, 200, 230, 20);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 450, 60, 50);

        j4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        j4.setText("Female");
        j4.setOpaque(false);
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        add(j4);
        j4.setBounds(190, 390, 70, 25);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(140, 450, 50, 50);

        firstnamefield3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        firstnamefield3.setText("Last Name ");
        firstnamefield3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                firstnamefield3MouseDragged(evt);
            }
        });
        firstnamefield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefield3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefield3FocusLost(evt);
            }
        });
        firstnamefield3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefield3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                firstnamefield3MouseReleased(evt);
            }
        });
        firstnamefield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefield3ActionPerformed(evt);
            }
        });
        add(firstnamefield3);
        firstnamefield3.setBounds(60, 170, 230, 20);

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel16.setText("BirthDate :");
        add(jLabel16);
        jLabel16.setBounds(60, 330, 70, 10);

        j3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        j3.setText("Male");
        j3.setOpaque(false);
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        add(j3);
        j3.setBounds(110, 390, 60, 20);

        firstnamefield.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        firstnamefield.setText("type of work  ");
        firstnamefield.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                firstnamefieldMouseDragged(evt);
            }
        });
        firstnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefieldFocusLost(evt);
            }
        });
        firstnamefield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefieldMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                firstnamefieldMouseReleased(evt);
            }
        });
        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });
        add(firstnamefield);
        firstnamefield.setBounds(60, 290, 230, 20);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Gender :");
        add(jLabel3);
        jLabel3.setBounds(60, 390, 50, 20);

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(380, 150, 100, 20);

        jComboBox2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBox2.setSelectedIndex(2);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2);
        jComboBox2.setBounds(130, 330, 40, 20);

        jComboBox4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox4.setSelectedIndex(5);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        add(jComboBox4);
        jComboBox4.setBounds(180, 330, 41, 20);

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(230, 330, 60, 20);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel1.setText("Employee Information");
        add(jLabel1);
        jLabel1.setBounds(70, 30, 210, 70);

        jTextField6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField6.setText("City ");
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        add(jTextField6);
        jTextField6.setBounds(60, 260, 100, 20);

        jTextField7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField7.setText("Street ");
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        add(jTextField7);
        jTextField7.setBounds(170, 260, 120, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
shi1 s=new shi1();
s.start();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void firstnamefield2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2MouseDragged

    private void firstnamefield2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2FocusGained

    private void firstnamefield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield2FocusLost
        if(firstnamefield2.getText().equals(""))
        firstnamefield2.setText("Minit ");        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2FocusLost

    private void firstnamefield2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield2MouseClicked
                if(firstnamefield2.getText().equals("Minit "))
        firstnamefield2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2MouseClicked

    private void firstnamefield2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2MouseReleased

    private void firstnamefield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2ActionPerformed

    private void firstnamefield1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield1MouseDragged

    private void firstnamefield1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield1FocusGained

    private void firstnamefield1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield1FocusLost
        if(firstnamefield1.getText().equals(""))
        firstnamefield1.setText("First Name ");
    }//GEN-LAST:event_firstnamefield1FocusLost

    private void firstnamefield1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield1MouseClicked
               if(firstnamefield1.getText().equals("First Name "))
        firstnamefield1.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield1MouseClicked

    private void firstnamefield1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield1MouseExited

    private void firstnamefield1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield1MouseReleased

    private void firstnamefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield1ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void firstnamefield4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield4MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield4MouseDragged

    private void firstnamefield4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield4FocusGained

    private void firstnamefield4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield4FocusLost
        if(firstnamefield4.getText().equals(""))
        firstnamefield4.setText("Salary ");        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield4FocusLost

    private void firstnamefield4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield4MouseClicked
                if(firstnamefield4.getText().equals("Salary "))
        firstnamefield4.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield4MouseClicked

    private void firstnamefield4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield4MouseReleased

    private void firstnamefield4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefield4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield4ActionPerformed

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        if(jTextField10.getText().equals(""))
        jTextField10.setText("Id ") ;     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        if(jTextField10.getText().equals("Id "))
        jTextField10.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void firstnamefield3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield3MouseDragged

    private void firstnamefield3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield3FocusGained

    private void firstnamefield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield3FocusLost
        if(firstnamefield3.getText().equals(""))
        firstnamefield3.setText("Last Name ");      // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield3FocusLost

    private void firstnamefield3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield3MouseClicked
        if(firstnamefield3.getText().equals("Last Name "))
        firstnamefield3.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield3MouseClicked

    private void firstnamefield3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield3MouseReleased

    private void firstnamefield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield3ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void firstnamefieldMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefieldMouseDragged

    }//GEN-LAST:event_firstnamefieldMouseDragged

    private void firstnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusGained

    }//GEN-LAST:event_firstnamefieldFocusGained

    private void firstnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefieldFocusLost
        if(firstnamefield.getText().equals(""))
        firstnamefield.setText("type of work  ");
    }//GEN-LAST:event_firstnamefieldFocusLost

    private void firstnamefieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefieldMouseClicked
                if(firstnamefield.getText().equals("type of work  "))

        firstnamefield.setText("");
    }//GEN-LAST:event_firstnamefieldMouseClicked

    private void firstnamefieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefieldMouseReleased

    }//GEN-LAST:event_firstnamefieldMouseReleased

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefieldActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
       if(jTextField6.getText().equals(""))
        jTextField6.setText("City ");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
               if(jTextField6.getText().equals("City "))

        jTextField6.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
               if(jTextField7.getText().equals(""))
        jTextField7.setText("Street ");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
                       if(jTextField7.getText().equals("Street "))

        jTextField7.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JTextField firstnamefield1;
    private javax.swing.JTextField firstnamefield2;
    private javax.swing.JTextField firstnamefield3;
    private javax.swing.JTextField firstnamefield4;
    private javax.swing.ButtonGroup gg1;
    private javax.swing.ButtonGroup gg2;
    private javax.swing.JRadioButton j1;
    private javax.swing.JRadioButton j2;
    private javax.swing.JRadioButton j3;
    private javax.swing.JRadioButton j4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
